apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - "/etc/prometheus/rules/*.yml"

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager-service.monitoring.svc.cluster.local:9093

    scrape_configs:
      # Prometheus 자체 모니터링
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # API Gateway 모니터링
      - job_name: 'gateway'
        static_configs:
          - targets: ['gateway-service.restaurant-system.svc.cluster.local:9090']
        metrics_path: /metrics
        scrape_interval: 10s

      # User Service 모니터링
      - job_name: 'user-service'
        static_configs:
          - targets: ['user-service.restaurant-system.svc.cluster.local:9090']
        metrics_path: /metrics
        scrape_interval: 10s

      # IoT Service 모니터링
      - job_name: 'iot-service'
        static_configs:
          - targets: ['iot-service.restaurant-system.svc.cluster.local:9090']
        metrics_path: /metrics
        scrape_interval: 10s

      # PostgreSQL 모니터링
      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres-service.restaurant-system.svc.cluster.local:9187']
        metrics_path: /metrics
        scrape_interval: 30s

      # Redis 모니터링
      - job_name: 'redis'
        static_configs:
          - targets: ['redis-service.restaurant-system.svc.cluster.local:9121']
        metrics_path: /metrics
        scrape_interval: 30s

      # Kubernetes 노드 모니터링
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics

      # Kubernetes 서비스 모니터링
      - job_name: 'kubernetes-service-endpoints'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__ 