name: ai-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - tensorflow=2.15.0
  - keras=2.15.0
  - numpy=1.24.3
  - pandas=2.3.0
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - plotly=5.15.0
  - statsmodels=0.14.0
  - prophet=1.1.4
  - nltk=3.8.1
  - textblob=0.17.1
  - joblib=1.3.2
  - jupyter
  - ipykernel
  - pip
  - pip:
    - streamlit==1.28.0
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - pydantic==2.5.0 