apiVersion: v2
name: restaurant-management
description: A Helm chart for Restaurant Management System Microservices
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - restaurant
  - management
  - microservices
  - kubernetes
home: https://github.com/restaurant/management
sources:
  - https://github.com/restaurant/management
maintainers:
  - name: Restaurant Team
    email: team@restaurant.com
dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: prometheus
    version: 25.x.x
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    version: 7.x.x
    repository: https://grafana.github.io/helm-charts 