apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-config
  namespace: monitoring
data:
  falco.yaml: |
    # Falco 설정 파일
    # 런타임 보안 모니터링을 위한 설정
    
    # 로깅 설정
    log_level: info
    log_stderr: true
    log_syslog: false
    log_file: /var/log/falco.log
    
    # 출력 설정
    outputs:
      - console
      - program: "curl -d @- -X POST http://alertmanager-service.monitoring.svc.cluster.local:9093/api/v1/alerts"
    
    # 웹서버 설정
    webserver:
      enabled: true
      listen_port: 9376
      ssl_enabled: false
      ssl_certificate: /etc/falco/falco.pem
    
    # gRPC 설정
    grpc:
      enabled: true
      bind_address: "0.0.0.0:5060"
      threadiness: 4
    
    # 메트릭 설정
    metrics:
      enabled: true
      include:
        - "falco.rules.*"
        - "falco.events.*"
    
    # 규칙 설정
    rules_file:
      - /etc/falco/falco_rules.yaml
      - /etc/falco/rules.d/
    
    # 출력 형식
    output_format: json
    
    # 이벤트 버퍼 설정
    buffer_events: true
    events_buffer_size: 1000
    
    # 스로틀링 설정
    rate_limit: 100
    rate_limit_window: 60
    
    # 시간 설정
    time_format_iso_8601: true
    
    # 호스트 설정
    hostname: "restaurant-cluster"
    
    # 보안 설정
    syscall_event_drops:
      action: log
      rate: 0.33
      max_burst: 100
    
    # 메모리 설정
    memory_dump_enabled: false
    memory_dump_path: /tmp/falco-memory.dump 