apiVersion: v1
kind: Secret
metadata:
  name: mtls-ca-cert
  namespace: restaurant-system
type: Opaque
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCg==  # Base64 encoded CA certificate
---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-mtls-cert
  namespace: restaurant-system
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCg==  # Base64 encoded server certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCg==  # Base64 encoded server key
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCg==  # Base64 encoded CA certificate
---
apiVersion: v1
kind: Secret
metadata:
  name: user-mtls-cert
  namespace: restaurant-system
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCg==  # Base64 encoded server certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCg==  # Base64 encoded server key
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCg==  # Base64 encoded CA certificate
---
apiVersion: v1
kind: Secret
metadata:
  name: iot-mtls-cert
  namespace: restaurant-system
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCg==  # Base64 encoded server certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCg==  # Base64 encoded server key
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCg==  # Base64 encoded CA certificate 