apiVersion: v1
kind: Secret
metadata:
  name: restaurant-app-secrets
  namespace: restaurant-system
type: Opaque
data:
  # Base64로 인코딩된 값들 (실제 환경에서는 적절한 값으로 변경)
  SECRET_KEY: eW91ci1zZWNyZXQta2V5LWhlcmU=  # your-secret-key-here
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleQ==  # your-jwt-secret-key
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # password
  REDIS_PASSWORD: cmVkaXNwYXNzd29yZA==  # redispassword
  
  # SSL 인증서 (실제 환경에서는 적절한 인증서로 변경)
  SSL_CERT: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCg==  # 예시 인증서
  SSL_KEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCg==   # 예시 키 