apiVersion: v1
kind: Namespace
metadata:
  name: your_program-system
  labels:
    name: your_program-system
    app: your_program-management
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    app: monitoring
    environment: production 
