apiVersion: v1
kind: Namespace
metadata:
  name: restaurant-system
  labels:
    name: restaurant-system
    app: restaurant-management
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    app: monitoring
    environment: production 