apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurant-app-config
  namespace: restaurant-system
data:
  # API Gateway 설정
  GATEWAY_PORT: "5000"
  USER_SERVICE_URL: "http://user-service:5001"
  STAFF_SERVICE_URL: "http://staff-service:5002"
  INVENTORY_SERVICE_URL: "http://inventory-service:5003"
  ORDER_SERVICE_URL: "http://order-service:5004"
  ANALYTICS_SERVICE_URL: "http://analytics-service:5005"
  IOT_SERVICE_URL: "http://iot-service:5006"
  NOTIFICATION_SERVICE_URL: "http://notification-service:5007"
  AI_SERVICE_URL: "http://ai-service:5008"
  
  # User Service 설정
  USER_SERVICE_PORT: "5001"
  USER_DB_PATH: "/app/user_service.db"
  
  # IoT Service 설정
  IOT_SERVICE_PORT: "5006"
  IOT_DB_PATH: "/app/iot_service.db"
  
  # 데이터베이스 설정
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "restaurant_microservices"
  POSTGRES_USER: "postgres"
  
  # Redis 설정
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # 로깅 설정
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  
  # 모니터링 설정
  METRICS_PORT: "9090"
  HEALTH_CHECK_INTERVAL: "30s"
  
  # 보안 설정
  JWT_SECRET: "your-secret-key-here"
  SESSION_TIMEOUT: "24h"
  
  # 성능 설정
  MAX_CONNECTIONS: "100"
  REQUEST_TIMEOUT: "30s"
  RATE_LIMIT: "1000" 