apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: restaurant-system
  labels:
    app: gateway
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        version: v1
    spec:
      containers:
      - name: gateway
        image: restaurant-gateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: GATEWAY_PORT
          valueFrom:
            configMapKeyRef:
              name: restaurant-app-config
              key: GATEWAY_PORT
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: restaurant-app-config
              key: USER_SERVICE_URL
        - name: STAFF_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: restaurant-app-config
              key: STAFF_SERVICE_URL
        - name: INVENTORY_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: restaurant-app-config
              key: INVENTORY_SERVICE_URL
        - name: ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: restaurant-app-config
              key: ORDER_SERVICE_URL
        - name: ANALYTICS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: restaurant-app-config
              key: ANALYTICS_SERVICE_URL
        - name: IOT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: restaurant-app-config
              key: IOT_SERVICE_URL
        - name: NOTIFICATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: restaurant-app-config
              key: NOTIFICATION_SERVICE_URL
        - name: AI_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: restaurant-app-config
              key: AI_SERVICE_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: restaurant-app-secrets
              key: SECRET_KEY
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: gateway-logs
          mountPath: /app/logs
      volumes:
      - name: gateway-logs
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-hpa
  namespace: restaurant-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 