apiVersion: apps/v1
kind: Deployment
metadata:
  name: plugin-monitoring-system
  namespace: restaurant-system
  labels:
    app: plugin-monitoring
    component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plugin-monitoring
  template:
    metadata:
      labels:
        app: plugin-monitoring
        component: monitoring
    spec:
      containers:
      - name: plugin-monitoring
        image: your-program/plugin-monitoring:latest
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: PLUGIN_MONITORING_ENABLED
          value: "true"
        - name: PLUGIN_BACKUP_ENABLED
          value: "true"
        - name: PLUGIN_ALERT_ENABLED
          value: "true"
        - name: PLUGIN_MONITORING_INTERVAL
          value: "300"
        - name: PLUGIN_BACKUP_INTERVAL
          value: "3600"
        - name: PLUGIN_ALERT_INTERVAL
          value: "30"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: secret-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: plugin-data
          mountPath: /app/plugins
        - name: backup-data
          mountPath: /app/backups
        - name: monitoring-data
          mountPath: /app/monitoring
        - name: logs
          mountPath: /app/logs
        livenessProbe:
          httpGet:
            path: /api/admin/plugin-monitoring/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/admin/plugin-monitoring/health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: plugin-data
        persistentVolumeClaim:
          claimName: plugin-data-pvc
      - name: backup-data
        persistentVolumeClaim:
          claimName: backup-data-pvc
      - name: monitoring-data
        persistentVolumeClaim:
          claimName: monitoring-data-pvc
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: plugin-monitoring-service
  namespace: restaurant-system
  labels:
    app: plugin-monitoring
spec:
  selector:
    app: plugin-monitoring
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plugin-data-pvc
  namespace: restaurant-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-data-pvc
  namespace: restaurant-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-data-pvc
  namespace: restaurant-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plugin-monitoring-ingress
  namespace: restaurant-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: plugin-monitoring.yourprogram.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plugin-monitoring-service
            port:
              number: 5000
  tls:
  - hosts:
    - plugin-monitoring.yourprogram.com
    secretName: plugin-monitoring-tls
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: plugin-monitoring-hpa
  namespace: restaurant-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: plugin-monitoring-system
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60 