apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: your_program-system
  labels:
    app: gateway
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  - port: 443
    targetPort: 5000
    protocol: TCP
    name: https
  selector:
    app: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: your_program-system
  labels:
    app: user-service
spec:
  type: ClusterIP
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: user-service
---
apiVersion: v1
kind: Service
metadata:
  name: iot-service
  namespace: your_program-system
  labels:
    app: iot-service
spec:
  type: ClusterIP
  ports:
  - port: 5006
    targetPort: 5006
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: iot-service
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: your_program-system
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: your_program-system
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: redis 
